### ISSUE TITLE
Detect the direction of scrolling

### ISSUE THREAD

**Issue by philecom** [HHogg/angular-scrollstop#2]
Great directive I must say. I will like to know if it can detect which direction is the scrolling whether Up or Down? thank you

**Comment by HHogg** [comment]
Thanks @philecom :) It is possible and I have implemented that in a similar directive, I'll add this in a bit later today as a property on the event.

**Comment by philecom** [comment]
That will be great. I am looking forward to that....

**Comment by HHogg** [comment]
@philecom Sorry for the late action on this. I've now added this, please check it out and let me know if it does what you need. Thanks.
