### ISSUE TITLE
$ bower install angular-scroll

### ISSUE THREAD

**Issue by johnjspiteri** [HHogg/angular-scrollstop#3]
@HHogg - In your README you referenced - $ bower install angular-scroll

 There is another repo "angular-scroll", believe you meant = $ bower install angular-scrollstop

Thank you for the component, great work.

**Comment by HHogg** [comment]
Ah not sure what happened there, thanks for spotting it. Have updated. I wasn't sure if anybody was still using this... I may revisit and make sure it's still working with the latest versions!
